#开发环境配置
server:
  #端口
  port: 8880
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.yj.oa.project.mapper: debug
#数据源
spring:
  datasource:
    url: jdbc:mysql://106.14.226.138:3306/oa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


  #######################
  #                     #
  #  RabbitMq           #
  #                     #
  #######################


  rabbitmq:
    addresses: memoryoverflow.cn
    password: 

    # 开启消息确认机制
    publisher-returns: true
    publisher-confirms: true

    # 开启mandatorytrue, basic.return方法将消息返还给生产者
    template:
      ##  启用强制信息 消息发送失败返回到队列中
      mandatory: true
    listener:
      simple:
        # 最小的消费者数量
        concurrency: 1
        # 最大的消费者数量
        max-concurrency: 1
        # 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
        prefetch: 1
        # 监听重试是否可用
        retry:
          enabled: true

        # 表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
        # manual 手动确认-用户必须通过通道感知侦听器确认/确认。
        acknowledge-mode: manual

      # 决定被拒绝的消息是否重新入队；默认是true（与参数acknowledge-mode有关系）
      direct:
        default-requeue-rejected: false


# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yj.oa.project.po
  configuration:
    map-underscore-to-camel-case: true



